sudo: false
dist: trusty
language: java
jdk:
- oraclejdk8
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start --noreset
- sleep 3
before_install:
  - LATEST=2.30
  - wget https://chromedriver.storage.googleapis.com//chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d chromedriver
  - export PATH=/Users/nigel.charman/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/var/jenv/shims:/Users/nigel.charman/.dotfiles/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/nigel.charman/bin:/Users/nigel.charman/.dotfiles/vendor/rbenv/bin:/Users/nigel.charman/source/concordion/concordion-scope-examples/chromedriver
addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
branches:
  except:
    - master
