services:
  - xvfb
language: java
jdk:
- openjdk8
addons:
  chrome: stable
before_install:
  - sudo apt-get update
  - sudo apt-get install chromium-chromedriver    
before_script:
  - sleep 3
branches:
  except:
    - master
